---
- hosts: linux
  ignore_errors: yes
  tasks:
  - name: print output
    shell: ls -l test.text
    register: output
  - debug: msg="standard output={{ output.stdout }}"
  - debug: msg="standard error={{ output.stderr }}"
